version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newrelic
    working_dir: '/api'
    tty: true
    volumes:
        - ./api:/api
    env_file: .env